config/routes.rb
Rails.application.routes.draw do

root 'billboards#index'

resources :billboards
resources :artist
resources :song   

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/billboard.rb
class Billboard < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :destroy]
  def index
    @artist = Artist.all
  end

  def show
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path(@artist)
    else
      render :new
    end
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end

  def set_artist
    @artist = artist.find(params[:id])
  end
  end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :destroy]
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path(@billboard)
    else
      render :new
    end
  end

  def new
    @billboard = Billboard.new
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboard_path(@billboard)
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

private

  def billboard_params
    params.require(:billboard).permit(:name, :description)
  end

  def set_billboard
    @billboard = Billboard.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :destroy]
  def index
    @songs = Song.all
  end

  def show
  end

  def create
    @song = Song.new(song_params)
    if @billboard.save
      redirect_to songs_path(@song)
    else
      render :new
    end
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

private

  def song_params
    params.require(:song).permit(:name, :duration, :genre, :artist)
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/edit.html.erb
<h1>Billboard</h1>

app/views/billboards/index.html.erb
<h1> Top Billboards </h1>
<hr />

<%= link_to 'New Entry', new_billboard_path %>

<% if @billboards.empty? %>
  <h3> No current Billboards </h3>
  <% else %>
  <ul>
    <% @billboards.each do |billboards| %>
    <li>
      <%= link_to billboards.name, billboard_path(billboards)%>
      <%= link_to 'Delete', billboard_path(billboards), method: :delete %>
      <%= link_to 'Edit', edit_billboard_path(billboards) %>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/billboards/new.html.erb
<h1> Create New Billboard </h1>
<hr />

<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />

  <%= f.submit %>
<% end %>

app/views/billboards/show.html.erb
<h1>Billboards#show</h1>
<p>Find me in app/views/billboards/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>